services:
  db:
    image: postgres:15
    container_name: postgres_db_tarifario
    restart: always
    environment:
      POSTGRES_USER: user_p
      POSTGRES_PASSWORD: password_p
      POSTGRES_DB: tarifario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_tarifario:/var/lib/postgresql/data

volumes:
  postgres_data_tarifario: